apiVersion: apps/v1
kind: Deployment
metadata:
  name: theme-park-ride-deployment
  namespace: dev
  labels:
    app: theme-park-ride
spec:
  replicas: 3
  selector:
    matchLabels:
      app: theme-park-ride
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: theme-park-ride
    spec:
      containers:
        - name: theme-park-ride
          image: registry.gitlab.com/jhiberne/theme-park-ride-gradle:latest
          ports:
            - containerPort: 5000