apiVersion: v1
kind: Service
metadata:
  name: theme-park-ride-service
  namespace: dev
spec:
  type: NodePort  
  selector:
    app: theme-park-ride
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 5000    
      nodePort: 30085     