spring:
  application:
    name: theme-park-ride-gradle
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}

server:
  port: ${SERVER_PORT:5000}

info:
  app:
    version: ${APP_VERSION:unknown}
    commit: ${APP_COMMIT:unknown}
    branch: ${APP_BRANCH:unknown}

management:
  endpoints:
    web:
      exposure:
        include: health,info
